ALTER TABLE clients ADD COLUMN IF NOT EXISTS lang TEXT NOT NULL DEFAULT 'ru';

ALTER TABLE bots ADD COLUMN IF NOT EXISTS channel_username TEXT;

CREATE TABLE IF NOT EXISTS admin_invites (
    id SERIAL PRIMARY KEY,
    bot_id INT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '24 hours'
);

CREATE INDEX IF NOT EXISTS idx_admin_invites_code ON admin_invites(code);
